# adapted from https://github.com/purcell/package-lint/blob/master/.github/workflows/test.yml
name: scimax

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.1

    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Install aspell
      run: sudo apt-get install -y aspell
      
    - uses: actions/checkout@v2
    - name: org-publish
      run: |
        emacs -batch -nw -l publish.el

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./scimax-eln/docs
        
